#!/usr/bin/env bash

CONFIG="$HOME/.config/mouse-remap.conf"
STATE_DIR="/tmp/mouse_remap"
rm -rf "$STATE_DIR" > /dev/null
mkdir -p "$STATE_DIR"
declare -A STATE

DEBUG="${DEBUG:-0}"

log() {
    local level="$1"
    shift
    if [[ "$level" == "DEBUG" && "$DEBUG" != "1" ]]; then
        return
    fi
    echo "[$level] $(date '+%F %T') $*"
}

# Parse mappings into xbindkeys format
parse_mappings() {
    local line="$1"
    echo "$line" | tr ',' '\n' | while read -r mapping; do
        mapping=$(echo "$mapping" | xargs)  # trim whitespace
        [[ -z "$mapping" ]] && continue
        local lhs=$(echo "$mapping" | cut -d'=' -f1 | xargs)
        local rhs=$(echo "$mapping" | cut -d'=' -f2 | xargs)
        echo "\"xdotool key --clearmodifiers $rhs\""
        echo "  $lhs"
    done
}

# Generate xbindkeys config for an app
generate_xbindkeys_config() {
    local app="$1"
    local buttons="$2"
    local keys="$3"
    local file="$STATE_DIR/$app.scm"
    > "$file"

    [[ -n "$buttons" ]] && parse_mappings "$buttons" >> "$file"
    [[ -n "$keys" ]] && parse_mappings "$keys" >> "$file"

    echo "$file"
}

log INFO "Starting mouse remap daemon using config: $CONFIG"

# kill all the xbindkeys instances generated by potential prior instances
for f in "$TARGET_DIR"/*; do
    if [[ -f "$f" ]]; then
        pkill "xbindkeys -f $f" 2>/dev/null
    fi
done


while true; do
    match=""
    app=""
    mappings=""

    while IFS= read -r line; do
        # Detect [Section]
        if [[ "$line" =~ ^\[(.+)\]$ ]]; then
            app="${BASH_REMATCH[1]}"
            match=""
            mappings=""
        elif [[ "$line" =~ ^match ]]; then
            match=$(echo "$line" | cut -d'=' -f2- | xargs)
        elif [[ "$line" =~ ^mappings ]]; then
            mappings=$(echo "$line" | cut -d'=' -f2- | xargs)

            if [[ -z "$match" ]]; then
                match="$app" # fallback to section name
            fi


            # Determine if process is running
            if pgrep -f -- "$match" >/dev/null; then
                if [[ "${STATE[$app]}" != "active" ]]; then
                    log INFO "Found process for [$app]"
                    if [ ! -f "$STATE_DIR/$app.pid" ]; then
                        config_file=$(generate_xbindkeys_config "$app" "$mappings")
                        if xbindkeys -f "$config_file" & then
                            echo $! > "$STATE_DIR/$app.pid"
                            log INFO "Applied remap for [$app] using $config_file"
                        else
                            log ERROR "Failed to start xbindkeys for [$app]"
                        fi
                    fi
                    STATE[$app]="active"
                fi
            else
                if [[ "${STATE[$app]}" != "inactive" ]]; then
                    log INFO "No process found for [$app] (removing remap if active)"
                    if [ -f "$STATE_DIR/$app.pid" ]; then
                        kill $(cat "$STATE_DIR/$app.pid") 2>/dev/null
                        rm "$STATE_DIR/$app.pid"
                        log INFO "Removed remap for [$app]"
                    fi
                    STATE[$app]="inactive"
                fi
            fi
        fi
    done < "$CONFIG"

    sleep 2
done

